# -*- coding: utf-8 -*-
"""model building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176pNUHYj3bide4qaAlFn0rm_3e_7-T3j
"""

import pandas as pd

df = pd.read_csv('traffic_data.csv')
df.head()

df = df.drop(columns = ['Speed', 'Energy Consumption','Economic Condition'])

df.head()

df = df.dropna()

import sklearn
sklearn.set_config(transform_output='pandas')

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import GridSearchCV

x = df.iloc[:, :-1]
y = df['Traffic Density']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

column_transformer = ColumnTransformer(
      transformers=[
              ('ohe', OneHotEncoder(sparse_output = False), ['City', 'Vehicle Type', 'Weather']),
              ('Oe',OrdinalEncoder(),['Day Of Week'])

      ],
      remainder='passthrough'
)

pipeline = Pipeline(steps=[
      ('preprocessor', column_transformer),
      ('regressor', LinearRegression())
])

param_grid = {
      'regressor__fit_intercept': [True, False]
}


grid_search = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=5, scoring='neg_mean_absolute_error')

grid_search.fit(x_train,y_train)

y_pred = grid_search.predict(x_test)

from sklearn.metrics import mean_squared_error, mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)
print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'Root Mean Squared Error: {rmse}')

import pickle
with open('peak.pkl', 'wb') as file:
      pickle.dump(grid_search, file)

